project:
  type: website
  output-dir: _site
  resources:
    - output/**/*.mp4

website:
  title: "envisionboxbio-apetrack"

format:
  html:
    theme: cosmo
    toc: true
    toc-expand: 2
    code-copy: true

execute:
  echo: false
